mysql:
  image: mysql:8.0.33
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=ds1

postgres:
  image: postgres:15.3
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_PASSWORD=secret
    - POSTGRES_DB=ds2